apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tms-min-side-topp
  namespace: min-side
  labels:
    team: min-side
spec:
  envFrom:
    - secret: tms-min-side-topp-secrets
  image: {{version}}
  port: 7300
  liveness:
    path: /tms-min-side-topp/internal/isAlive
    initialDelay: 10
  readiness:
    path: /tms-min-side-topp/internal/isReady
    initialDelay: 10
  prometheus:
    enabled: true
    path: /tms-min-side-topp/internal/metrics
  replicas:
    min: 2
    max: 4
  ingresses:
    - "https://person.dev.nav.no/tms-min-side-topp"
  resources:
    limits:
      cpu: "3"
      memory: 768Mi
    requests:
      cpu: "200m"
      memory: 512Mi
